FROM node:8.5.0

# Install Yarn
RUN \
     apt-get update \
  && apt-get -y install curl apt-transport-https \
  && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list \
  && apt-get update \
  && apt-get -y install yarn

RUN mkdir /app

COPY api/package.json yarn.lock /app/
WORKDIR /app
RUN yarn

COPY . /app/

RUN \
     node_modules/.bin/tsc
