#!/usr/bin/env bash

PROJ_NAME=autio

function finish {
  echo "Stopping..."
  docker-compose -p $PROJ_NAME stop

  # docker-compose -p $PROJ_NAME rm -f api
  # docker-compose -p $PROJ_NAME rm -f web-app
  echo "done."
}

trap finish EXIT

set -x
  docker-compose -p $PROJ_NAME build api \
  && docker-compose -p $PROJ_NAME up -d api \
  && echo "hold please..." \
  && sleep 2 \
  && docker-compose -p $PROJ_NAME logs -f --tail=100 api
STATUS=$?

exit $STATUS
